color: true
dry-run: null
hookfiles: ['dredd-hooks.js']
language: nodejs
require: null
server-wait: 3
init: false
custom: {}
names: false
only: []
reporter: []
output: []
header: []
sorted: true
user: null
inline-errors: false
details: false
method: ['GET']
loglevel: warning
path: []
config: ./dredd.yml
blueprint: quotes.apib
endpoint: 'http://quotes.darkscience.net'
