version: 2
jobs:
  build:
    working_directory: ~/circleci
    docker:
      - image: circleci/python:2.7-node
        environment:
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
          DEBUG: 1
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - run: |
          pip install pipenv
          pipenv install --dev
      - run: |
          pipenv run python manage.py test
      - run: npm install dredd@10.0.0
      - run: |
          pipenv run python manage.py syncdb --noinput
          pipenv run npx dredd
