version: 2
jobs:
  build:
    working_directory: ~/circleci
    docker:
      - image: circleci/python:2.7-node
        environment:
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - run: |
          pip install virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install mock
      - run: |
          source venv/bin/activate
          python manage.py test quotes
      - run: npm install dredd@10.0.0
      - run: |
          source venv/bin/activate
          python manage.py syncdb --noinput
          python manage.py migrate --noinput
          npx dredd
